/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2011 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/


int __thiscall IEventQueue::IEventQueue(void *this, int a2);
int __thiscall IEventQueue::ReInit(int this);
int __thiscall IEventQueue::Resize(int this, int a2);
int __thiscall IEventQueue::SendEvent(void *this, int a2, int a3, int a4);

	IEventQueue(size_t size);
	void SendEvent(long tick, const char * instrument, ITimeAction * action);
	void ReInit();
	void Resize(size_t size);

IEventQueue::IEventQueue(int size)
{
  /*
  a2=size;
  void *v2; 
  void *v3;
  char v5;   
  void *v6; 
  void *v7; 
  void *v8; 
  v8 = this;
  */
  this->bufsize=size;
  this->currentIndex=-1;
  this->executeIndex=-1;

  pthread_mutex_init(this->lock);
  pthread_cond_init(this->cond);
  pthread_spin_init(this->spinlock, 0);
  this->TickBuf=new(sizeof(long)*this->bufsize);
  this->InstrumentID=new(sizeof(char*)*this->bufsize);
  this->Actionbuf=new(sizeof(ITimeAction*)*this->bufsize);
  return;
}

IEventQueue::~IEventQueue()
{
    /*
       pthread_spin_destroy((char *)v6 + 12);
       pthread_cond_destroy((char *)v6 + 8);
       pthread_mutex_destroy((char *)v6 + 4);
       delete
       */
}

// 1F8: using guessed type void *IEventQueue___vftable_;
// B30: using guessed type int _RTC_CheckEsp(void);
// B50: using guessed type int __cdecl pthread_mutex_destroy(_DWORD);
// B54: using guessed type int __cdecl pthread_cond_destroy(_DWORD);
// B58: using guessed type int __cdecl pthread_spin_destroy(_DWORD);

void IEventQueue::ReInit()
{
    this->currentIndex=-1;
    this->executeIndex=-1;
}

void IEventQueue::Resize(int size)
{
    //delete,delete,delete
    //new,new,new
}

void IEventQueue::SendEvent(long tick, char * instrument, ITimeAction *action)
{
    /*
       a2=long
       a3=instrument
       a4=action
       */
    char v5; // [sp+Ch] [bp-D8h]@1
    int v6; // [sp+D0h] [bp-14h]@1
    void *v7; // [sp+DCh] [bp-8h]@1

    memset(&v5, -858993460, 0xD8u);
    v7 = this;
    pthread_spin_lock(this->lock);
    v6 = *((_DWORD *)v7 + 8) + 1;
    v6=this->currentIndex+1;
	int executeIndex;


    if ( v6 == this->executeIndex )
        v6 = 0;
    this->TickBuf[v6]=tick;
    this->InstrumentID[v6]=instrument;
    this->ActionBuf[v6]=action;
    this->currentIndex=v6;
    pthread_spin_unlock(this->lock);
    pthread_cond_signal(this->cond);
    return;
}
